name: Caller CI/CD Workflow

on:
  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  push:
    branches:
      - dev
      - test
      - prod
  pull_request:
    branches:
      - dev
      - test
      - prod

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-generic.yml@main
    with:
      pom_path: 'pom.xml'
      service: 'payments-service'
      target: ${{ github.ref_name }}
      SONAR_PROJECT:  ${{ vars.SONAR_PROJECT }}
    secrets: inherit
